### ISSUE TITLE
Ability to disable pluralization of schema

### ISSUE THREAD

**Issue by sagrawal31** [nestjs/mongoose#1038]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

For all the schema, [Mongoose append "s"](https://docs.nestjs.com/techniques/mongodb#:~:text=but%20with%20an%20additional%20%E2%80%9Cs%E2%80%9D%20at%20the%20end) that I'm trying to disable via the following code-

```typescript
// main.ts
import * as mongoose from 'mongoose';

async function bootstrap() {
    // This is not working 
    mongoose.pluralize(null);
    // ...
}
```

I also tried to call `mongoose.pluralize(null)` at two different places-

1. In the constructor of `AppModule`.
2. In the lifecycle event `onModuleInit` via `OnModuleInit`.

But still, the collection is being used in `cats` instead of `cat`.

## Expected behaviour

The schema collection should not be pluralized. 

## Minimal reproduction of the problem with instructions

Use any schema like-

```
@Schema()
export class Cat {

    @Prop({auto: true})
    _id: MongooseSchema.Types.ObjectId;

    @Prop()
    name: string;
}
```

## What is the motivation/use case for changing the behaviour?

We (I'm sure many other companies as well) do not prefer adding "s" at the end of each individual collection in MongoDB. Searched the existing issues in the GitHub repos and in StackOverflow. Found https://stackoverflow.com/a/54832791/2405040 but not working in NestJS.

Although, there is a workaround available i.e. `@Schema({collection: 'cat'})` but it's a non-convenient/non-DRY approach.

## Environment

<pre><code>
"@nestjs/common": "^8.0.6",
"@nestjs/config": "^1.0.1",
"@nestjs/core": "^8.0.6",
"@nestjs/mongoose": "^8.0.1",
 
For Tooling issues:
- Node version: v14.16.0
- Platform:  macOS Monterey

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
