### ISSUE TITLE
Unhandled promise rejections during MongooseModule initialization

### ISSUE THREAD

**Issue by ukito-pl** [nestjs/mongoose#1057]
### Did you read the migration guide?

- [ ] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

8.0.1 -> 9.0.0

### Describe the regression

Hi, 
I recently upgraded @nestjs/mongoose to 9.0.0 and mongoose to 6.0.9. 

Since then mongoose errors are not being caught. If there is any exception being thrown during establishing connection it results in unhandled promise rejection. In the snippet below I set retryAttempts to 10, but there is unhandled promise rejection after 1st failed connection attempt and there are no further attempts.

### Minimum reproduction code

```ts
@Module({
  imports: [
    MongooseModule.forRoot(
      'mongodb://user:pass@localhost:27020/main?authSource=admin',
      { retryAttempts: 10 },
    ),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```
Here is full reproduction repository: https://github.com/ukito-pl/nest-mongoose-bug

### Expected behavior

I expect that in case of connection error Mongoose will retry connection according to 'retryAttempts' option and will not cause unhandled promise rejections.

**Comment by ukito-pl** [comment]
Here is github repo: https://github.com/ukito-pl/nest-mongoose-bug

**Comment by gsaint** [comment]
Having the same issue here!

**Comment by jordanberry** [comment]
Experiencing the same, happy to help triage - appreciate the great framework 👍
