### ISSUE TITLE
MongooseCoreModule unable to resolve ModuleRef  from injection container

### ISSUE THREAD

**Issue by BitForger** [nestjs/mongoose#1060]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

7.x -> 9

### Describe the regression

I have made it all the way through the migration process up to the point where I'm trying to test in my local environment. When I start the application is gives me this error:

```
ERROR [ExceptionHandler] Nest can't resolve dependencies of the MongooseCoreModule (MongooseConnectionName, ?). Please make sure that the argument ModuleRef at index [1] is available in the MongooseCoreModule context.
```

### Minimum reproduction code

```ts
MongooseModule.forRootAsync({
  imports: [EnvModule], // a module importing classes that validate the environment variables
  useClass: ConfigService,
  connectionName: "dbname",
})
```

### Expected behavior

Application shouldn't error on startup

### Other

I'm completely lost as to what the problem could be.

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.
