### ISSUE TITLE
Typegoose Support

### ISSUE THREAD

**Issue by LukvonStrom** [nestjs/mongoose#108]
## I'm submitting a...
<pre><code>
[x] Feature request
</code></pre>

## Current behavior
When using this package I would need to define my interface/class and my model for Mongoose in two different files or at least at two places instead of one. 
This leads to ugly code and the need to keep them manually in sync. 
Typegoose (https://github.com/szokodiakos/typegoose) allows me to define all the relevant stuff in just one class and additionally would allow me to use `@nestjs/swagger`. 
At the moment it is not possible to use typegoose, as far as I know, because there is no option to access the underlying mongoose connection of this module, which I would need to supply to Typegoose.
As nestjs is making heavy use of Typescript, integrating Typegoose would be a great idea imho.

## Expected behavior
Support for injecting the connection from the MongooseModule into Typegoose or direct support for Typegoose via this module.

## What is the motivation / use case for changing the behavior?
Removing the need for a seperate interface when using mongoose models and making the life of Nest Developers easier.

**Comment by kamilmysliwiec** [comment]
We're considering supporting typegoose, but as a separate package (`@nestjs/typegoose`) :) Hopefully, we'll deliver it soon.
