### ISSUE TITLE
Support specifying the session when creating single documents

### ISSUE THREAD

**Issue by cloakedch** [nestjs/mongoose#1185]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, one of the ways of creating a new document is the following (Excerpt from example `06-mongoose`):

```ts
const doc = await this.catModel.create(createCatDto);
```

If one would want to wrap the creation of a document in a transaction, they could do it like this for example:

```ts
constructor(
    @InjectConnection() private connection: Connection,
    ...
) {}

...

const session = await this.connection.startSession();
await session.withTransaction(async (s) => {
  const doc = await this.userModel.create(createCatDto, { session: s });
});
await session.endSession();
```

However, the return type changes from

```ts
const doc: Cat & Document<any, any, any> & {
    _id: any;
}
```

to

```ts
const doc: (Cat & Document<any, any, any> & {
    _id: any;
})[]
```

, which is an array.

### Describe the solution you'd like

Be able to create a single document and specify a session.

### What is the motivation / use case for changing the behavior?

Be able to use `create()` in a transaction.

**Comment by jmcdo29** [comment]
What does Nest's wrapper have to do with base mongoose functionality? I'm not sure how this is related to us. IT should be opened in mongoose's repository
