### ISSUE TITLE
Prop decorator doesn't set proper type of property with mongoose options

### ISSUE THREAD

**Issue by Cartman720** [nestjs/mongoose#1186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am creating a schema where couple of string properties need to have mongoose `setters` and other options such as `default`, `trim` etc. However as a result Mongoose can't cast types on schema read and gives `Document` object instead of `String` and when I try to call JS built in `replace`, `match` and other string methods I get `TypeError: email.match is not a function` error. 

Here is the schema definition, where you can see that `email` property has setter and couple of other options. Interestingly, options does work, but type isn't set properly as I understand and we get `Document` instance instead of string.

```
@Schema({
  minimize: false,
  timestamps: true,
  toObject: {
    virtuals: true,
  },
  toJSON: {
    virtuals: true,
  },
})
export class User {
  _id: mongoose.Types.ObjectId;

  @Prop({ trim: true })
  firstname: string;

  @Prop({ trim: true })
  lastname: string;

  @Prop({ trim: true })
  name: string;

  @Prop({
    trim: true,
    sparse: true,
    unique: true,
  })
  username: string;
  
  @Prop({
    unique: true,
    sparse: true,
    trim: true,
    set: (v) => v?.toLowerCase(),
  })
  email: string;
}
```  

attaching screenshot of VSCode debugger, that clearly shows that `email` property threated as `Document`

![image](https://user-images.githubusercontent.com/12465135/148377021-894e6b3a-85a3-4386-8e27-0d9e36fead7b.png)

### Minimum reproduction code

N/A

### Expected behavior

Rather I would expected to get string property on read instead of `Document`.

### Package version

^9.0.1

### mongoose version

^6.0.13

### NestJS version

^8.0.0

### Node.js version

v14.18.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
