### ISSUE TITLE
Property errors on node_modules

### ISSUE THREAD

**Issue by NaturesProphet** [nestjs/mongoose#1197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

i reproduced the oficial tutorial here: https://docs.nestjs.com/techniques/mongodb

after install mongoose module and import it in app module, my app can't build.

### Minimum reproduction code

https://docs.nestjs.com/techniques/mongodb

### Steps to reproduce

nest new mongotest
npm install --save @nestjs/mongoose mongoose
import mongooseModule in appModule just like the tutorial:
@Module({
  imports: [MongooseModule.forRoot('mongodb://localhost/nest')]
})

npm run build   <-- cant build and show lots of Property errors in node_modules.

### Expected behavior

after import mongooseModule my project is crashing. it shouldnt

### Package version

9.0.2

### mongoose version

6.1.6

### NestJS version

7.6.0

### Node.js version

14.18.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
