### ISSUE TITLE
Bad error message at MongooseModule.forRoot

### ISSUE THREAD

**Issue by giovannyreyeso** [nestjs/mongoose#1201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you add a prop like ``` useCreateIndex: true ``` in MongooseModule.forRoot options can't connect to database but the correct error was: MongoParseError: option usecreateindex is not supported. 

i wasted hours for this bug. i need to do debug the code from @nestjs/moongose.

i will hope this help others.

 "@nestjs/common": "^8.0.0",
  "@nestjs/core": "^8.0.0",
  "@nestjs/mongoose": "^9.0.2",
  "mongoose": "^6.1.6",

### Minimum reproduction code

http://onmylocal

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5238726/149579439-232dd853-6820-457f-b2c6-bd228d202752.png)

### Expected behavior

print error: option usecreateindex is not supported

### Package version

^9.0.2

### mongoose version

^6.1.6

### NestJS version

^8.0.0

### Node.js version

v14.17.4

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

IDE: VSCode

**Comment by jmcdo29** [comment]
Did you wait for all of the reconnect tries to finish (there's 10 of them by default)

**Comment by giovannyreyeso** [comment]
Sorry i don't wait for all reconnect messages. 
You right, after 10 of them yes, the error print it. but in most case after one or two reconnect you will desist and stop de project looking for error

**Comment by kamilmysliwiec** [comment]
@giovannyreyeso you can disable retrying for debugging purposes.

**Comment by giovannyreyeso** [comment]
Yeah, but we must remember no everybody can do it that. but not problem, i wrote that for somebody in the future. i will close this bug.

Cheers
