### ISSUE TITLE
autopopulate not work with Azure CosmosDB's MongoDB API server version 4.0

### ISSUE THREAD

**Issue by vtrphan** [nestjs/mongoose#1207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm using nestjs and nestjs/mongoose package with Azure CosmosDB's MongoDB API, server version 4.0. However, `autopopulate` does not work with server version > 3.2.

`Autopopulate` used to work fine with server version 3.2. The problem is that starting with mongoose v6.1.0 and above, server version > 3.2 is required. But then `autopopulate` does not work anymore.

I'm using:

nestjs: 8.2.5
nestjs/mongoose: 9.0.2
mongoose: 6.1.6
node: 14 LTS
Azure CosmosDB's MongoDB API server version 4.0

### Minimum reproduction code

https://codesandbox.io/s/agitated-mountain-ibg1m?file=/src/user.service.ts

### Steps to reproduce

1. start a new terminal
2. run `npm run start`
3. refresh the view
4. in the result coming back, `registrationStatus.country` is still an ObjectId instead of a populated object

### Expected behavior

Note that if i populate the result manually (using `.populate` in the query), it works. In the returned result, `registrationStatus.country` is a populated object as expected (see the code in `user.service.ts`). However, the `autopopulate` property in the schemas does not work (see `registrationStatus` field in `user.schema.ts`)

The `autopopulate` is such a convenient feature to auto-populate fields that should always be populated in the result without having to manually call `.populate` in every query. Please investigate.

### Package version

9.0.2

### mongoose version

6.1.6

### NestJS version

8.2.5

### Node.js version

14.17.6

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
