### ISSUE TITLE
Nest can't resolve dependencies, When using "MongooseModuleOptions" in forRoot

### ISSUE THREAD

**Issue by richenyadav001** [nestjs/mongoose#1214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When running example --> https://github.com/nestjs/nest/tree/master/sample/06-mongoose

along with "MongooseModuleOptions"

MongooseModule.forRoot('mongodb://localhost:27017/test', {
            **_connectionName: 'xyz'_**
}),

### Minimum reproduction code

https://github.com/richenyadav001/06-mongoose

### Steps to reproduce

npm i
make sure mongo is running
npm run start

### Expected behavior

App should run successfully

### Package version

8.*

### mongoose version

9.0.2

### NestJS version

8.*

### Node.js version

12.16.3

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
