### ISSUE TITLE
IsClass checker for "inspectTypeDefinition" not working as expected?

### ISSUE THREAD

**Issue by Foxandxss** [nestjs/mongoose#1216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Say I have an entity like:

```
@Schema()
export class TimeEntry {
  @Prop({ required: false }) startPosition: GeoPoint;
}
```

This `GeoPoint` is a class:

```
export class GeoPoint {
  type: 'Point';
  coordinantes: number[];
}
```

When I do a:

`export const TimeEntrySchema = SchemaFactory.createForClass(TimeEntry);`

I get this error:

```
C:\Users\foxan\Documents\Programming\work\fichajes\node_modules\@nestjs\mongoose\dist\factories\definitions.factory.js:47
            optionsOrType = isClass ? optionsOrType : optionsOrType();
                                                      ^

TypeError: Class constructors cannot be invoked without 'new'
    at Function.inspectTypeDefinition (C:\Users\foxan\Documents\Programming\work\fichajes\node_modules\@nestjs\mongoose\dist\factories\definitions.factory.js:47:55)
    at Function.inspectTypeDefinition (C:\Users\foxan\Documents\Programming\work\fichajes\node_modules\@nestjs\mongoose\dist\factories\definitions.factory.js:56:39)
    at C:\Users\foxan\Documents\Programming\work\fichajes\node_modules\@nestjs\mongoose\dist\factories\definitions.factory.js:26:38
    at Array.forEach (<anonymous>)
    at Function.createForClass (C:\Users\foxan\Documents\Programming\work\fichajes\node_modules\@nestjs\mongoose\dist\factories\definitions.factory.js:25:86)     
    at Function.createForClass (C:\Users\foxan\Documents\Programming\work\fichajes\node_modules\@nestjs\mongoose\dist\factories\schema.factory.js:9:75)
    at Object.1838 (C:\Users\foxan\Documents\Programming\work\fichajes\dist\apps\fichajes-api\main.js:1:30582)
    at r (C:\Users\foxan\Documents\Programming\work\fichajes\dist\apps\fichajes-api\main.js:1:44921)
    at Object.1357 (C:\Users\foxan\Documents\Programming\work\fichajes\dist\apps\fichajes-api\main.js:1:32616)
    at r (C:\Users\foxan\Documents\Programming\work\fichajes\dist\apps\fichajes-api\main.js:1:44921)
```

The issue is here:

`const isClass = /^class\s/.test(Function.prototype.toString.call(optionsOrType));`

This expect a `class ` (class + space) and for some reason it returns `class{}`

If I change the rexep like `/^class\s*/` it works. But I am unsure that is a proper fix.

### Minimum reproduction code

Will provide if this is not enough data

### Expected behavior

Should work as expected.

### Package version

9.02

### mongoose version

6.1.6

### NestJS version

8.2.5

### Node.js version

14.18.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Other

The problem ocurrs by running a production build inside nx. It is a monorepo nx with nest + angular and building for prod and running the nest fails like that. Running it in development works just nice.

As my mind realized nest and nx are different projects, just tell me if this sound weird and I repro it right away.

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by Uter1007** [comment]
We have the same problem. When upgrading nest/mongoose and running a production build (nrwl nx context) - we get the same error.

**Comment by Foxandxss** [comment]
I am working on a more precise report because I cannot reproduce it with a clean install. I mean, if I create a new `nx` project with same dependencies, same code, it doesn't happen. It is like something gets in the way of upgrading, I just can't figure out what. But worry not, I am relentlessly working on seeing what it is and if its a bug in a different library, we will report it better.

**Comment by kamilmysliwiec** [comment]
Contributions are more than welcome so if you think we can just replace the current utility function with a better alternative, go for it!

**Comment by Foxandxss** [comment]
I mean, in my humble opinion the utility function could be improved but I am not happy changing something and ignoring why we came to this point. There is a bug somewhere and I need to find it out. Then we can either patch the original issue or improve this.

**Comment by Uter1007** [comment]
we will also try to inspect the issue - we are using a pageination plugin for mongoose -> I have this feeling that this could be maybe a factor or tsconfig need some tweaking.

**Comment by kamilmysliwiec** [comment]
If you're both using Nx, this is likely related to your webpack configuration

**Comment by Uter1007** [comment]
We will give this a extra look

**Comment by Uter1007** [comment]
https://stackoverflow.com/questions/70408168/nrwl-nx-monorepo-issue-nest-js-prod-build-with-optimization-flag-getting-invali

-> will post also into the nx repro

**Comment by jueschus** [comment]
seems to be an issue with the newest @nrwl/node version (13.1.2 works, 13.4.4 produces the errors with class names):
https://github.com/nrwl/nx/issues/8228

so the "isClass" check should work, but in this case it doesn't get the correct values.

**Comment by Foxandxss** [comment]
Yeah, that seems to be the cause. I wasn't optimizing my build so I was seeing different results in my demos. So if @kamilmysliwiec wants, we can close this and continue at nrwl/nx#8228
