### ISSUE TITLE
Whether a connection error handling method can be added

### ISSUE THREAD

**Issue by jiayisheji** [nestjs/mongoose#1247]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

```bash
[Nest] 6788  - 2022/02/11 pm5:53:31   ERROR [MongooseModule] Unable to connect to the database. Retrying (1)...
[Nest] 6788  - 2022/02/11 pm5:53:34   ERROR [MongooseModule] Unable to connect to the database. Retrying (2)...
[Nest] 6788  - 2022/02/11 pm5:53:37   ERROR [MongooseModule] Unable to connect to the database. Retrying (3)...
[Nest] 6788  - 2022/02/11 pm5:53:40   ERROR [MongooseModule] Unable to connect to the database. Retrying (4)...
[Nest] 6788  - 2022/02/11 pm5:53:43   ERROR [MongooseModule] Unable to connect to the database. Retrying (5)...
[Nest] 6788  - 2022/02/11 pm5:53:46   ERROR [MongooseModule] Unable to connect to the database. Retrying (6)...
[Nest] 6788  - 2022/02/11 pm5:53:49   ERROR [MongooseModule] Unable to connect to the database. Retrying (7)...
[Nest] 6788  - 2022/02/11 pm5:53:52   ERROR [MongooseModule] Unable to connect to the database. Retrying (8)...
[Nest] 6788  - 2022/02/11 pm5:53:55   ERROR [MongooseModule] Unable to connect to the database. Retrying (9)...
[Nest] 6788  - 2022/02/11 pm5:53:55   ERROR [ExceptionHandler] Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
```

Connection Error Failed to catch Error information.
Connection Error causes the `connectionFactory` method to not work.

Error handling is facilitated if a method is provided that can catch connection errors.

### Describe the solution you'd like

[https://github.com/nestjs/mongoose/blob/master/lib/mongoose-core.module.ts#L80](https://github.com/nestjs/mongoose/blob/master/lib/mongoose-core.module.ts#L80)

```ts
const {catchError} = require("rxjs/operators");

@Global()
@Module({})
export class MongooseCoreModule implements OnApplicationShutdown {
....
    const connectionProvider = {
      provide: mongooseConnectionName,
      useFactory: async (
        mongooseModuleOptions: MongooseModuleOptions,
      ): Promise<any> => {
        const {
          retryAttempts,
          retryDelay,
          connectionName,
          uri,
          connectionFactory,
         connectionError,
          ...mongooseOptions
        } = mongooseModuleOptions;

        const mongooseConnectionFactory =
          connectionFactory || ((connection) => connection);
        
       const mongooseConnectionError =
          connectionError || ((error) => {});
      
        return await lastValueFrom(
          defer(async () =>
            mongooseConnectionFactory(
              await mongoose
                .createConnection(
                  mongooseModuleOptions.uri as string,
                  mongooseOptions,
                )
                .asPromise(),
              mongooseConnectionName,
            ),
          ).pipe(
            handleRetry(
              mongooseModuleOptions.retryAttempts,
              mongooseModuleOptions.retryDelay,
            ),
            catchError(err => {
                  mongooseConnectionError(err);
                  throw error;
            })
          ),
        );
      },
      inject: [MONGOOSE_MODULE_OPTIONS],
    };
    .....
}
```

Just throw the error through the RXJS catchError.

### Teachability, documentation, adoption, migration strategy

> The connectionError method is used to capture connectionError information and report exceptions.

```ts
MongooseModule.forRootAsync({
    imports: [ConfigModule],
    useFactory: async (configService: ConfigService) => {
      return {
        uri: 'mongodb://localhost/test',
        connectionError: (error) => {
          console.log('MongooseModule connectionError', error);
          // Report connection error messages by email
        },
      };
    },
    inject: [ConfigService],
}),
```

### What is the motivation / use case for changing the behavior?

Currently, if the connection fails, the error cannot be caught and a remedy policy implemented.

The connectionFactory method is not executed after a connection error.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by jiayisheji** [comment]
@kamilmysliwiec  ok

**Comment by morelikeahumanraghu** [comment]
Trying to know why the connection with Mongodb was failing -- guessing this PR should give the stack trace.

**Comment by kblestarge** [comment]
I would like to gracefully fail by catching and logging the thrown error from a connection problem, but not breaking the app. Would this proposed solution work for my use-case?
What is the status of your PR, @jiayisheji?

**Comment by CodyTseng** [comment]
@jiayisheji  If you're busy, I'd be happy to implement this PR.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/mongoose/pull/1550

**Comment by vanHuong0202** [comment]
Hi, i use nest/mongose as module in my nestjs app, but the issue is that if mongo module hits error, my nestjs app can not start sucessfully, have any way that the nestjs app can ignore the mongo server error and continue to start, because for my app, mongodb is secondary db, not main db

**Comment by AndrewEmpik** [comment]
Hi! I also wish for that use case to be implemented for NestJS. I also hit the same problem that I need a graceful error handling in case MongoDB is disabled, but it looks like that still doesn't work :(
Or maybe anybody found a way to make a workaround?

**Comment by vanHuong0202** [comment]
> Hi! I also wish for that use case to be implemented for NestJS. I also hit the same problem that I need a graceful error handling in case MongoDB is disabled, but it looks like that still doesn't work :( Or maybe anybody found a way to make a workaround?

At the end, i did not use nest/mongoose any more, for instead,i create mongoose service, use it directly, manually initialize connection and close it when nestjs's api done.

**Comment by kamilmysliwiec** [comment]
If your app needs to work with Mongoose but you don't want to make it a required dependency (i.e., the app should still start even if MongoDB is unavailable), this package may not be suitable. The reason is that this library's mechanics are designed to establish a connection and create corresponding models based on that connection before the application fully starts (for the sake of dependency injection etc.)

If you dont need dependency injection, you should, following what @vanHuong0202 said above, create a connection manually (and manage it yourself, depending on what your project needs).
