### ISSUE TITLE
Argument of type '{ min: () => number; select: false; }' is not assignable to parameter of type 'PropOptions<any>'

### ISSUE THREAD

**Issue by meness** [nestjs/mongoose#1256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The code doesn't get compiled due to that error.

### Minimum reproduction code

https://gist.github.com/meness/880932ab260313945a90374f8d51ccf3

### Steps to reproduce

```typescript
@Prop({ min: Date.now, select: false })
  tokenExpiresAt: Date;
```

### Expected behavior

That configuration should work!

### Package version

9.0.2

### mongoose version

6.2.1

### NestJS version

8.2.1

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Update `mongoose` package to the latest version and it will work as expected.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
