### ISSUE TITLE
Cant import mongoose.

### ISSUE THREAD

**Issue by mkbrdigital** [nestjs/mongoose#127]
![mongoose](https://user-images.githubusercontent.com/49996023/63314107-04775080-c2dd-11e9-9ec7-077f3652c7dd.png)

Could not find a declaration file for module 'mongoose'. '/home/dev/Documents/projects/nest/petshop/node_modules/mongoose/index.js' implicitly has an 'any' type.
  Try `npm install @types/mongoose` if it exists or add a new declaration (.d.ts) file containing `declare module 'mongoose';`

Nest: 6.6.4
NodeJS: 12.7.0
Typescript: 3.5.3

package.json
```json
 "dependencies": {
    "@nestjs/common": "^6.0.0",
    "@nestjs/core": "^6.0.0",
    "@nestjs/mongoose": "^6.1.2",
    "@nestjs/platform-express": "^6.0.0",
    "mongoose": "^5.6.9",
    "reflect-metadata": "^0.1.12",
    "rimraf": "^2.6.2",
    "rxjs": "^6.3.3"
  },
```

**Comment by mkbrdigital** [comment]
https://github.com/nestjs/mongoose/blob/master/index.d.ts

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
