### ISSUE TITLE
No event emit while createConnection

### ISSUE THREAD

**Issue by amustaque97** [nestjs/mongoose#1290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In current version of package, connection is not able to emit event while calling `createConnection` mongoose function. This is happening after merging PR  https://github.com/nestjs/mongoose/pull/1083 and similar changes in other area of code.

In order to test this bug, I reverted the changes locally and then it started working as expected. All `connectionStates` were working fine but then I started facing issue regarding `InjectConnection` which you already solved with the mentioned PR https://github.com/nestjs/mongoose/pull/1083. I feel this is a bit tricky to fix. 

### Minimum reproduction code

https://github.com/amustaque97/nestjs-mongoose-no-event

### Steps to reproduce

1. `npm i`
2. `npm start:dev`
3. You will see line number 11 printed https://github.com/amustaque97/nestjs-mongoose-no-event/blob/main/src/app.module.ts#L11
4. `connected` will not be printed on console https://github.com/amustaque97/nestjs-mongoose-no-event/blob/main/src/app.module.ts#L12

### Expected behavior

After running server, it should print both the console statements. 

### Package version

9.0.3

### mongoose version

6.2.7

### NestJS version

8.0.0

### Node.js version

16.13.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
What's the reason for wanting to listen for the connection event? With [`asPromise()`](https://mongoosejs.com/docs/api.html#connection_Connection-asPromise) mongoose doesn't resolve the promise until the connection succeeds (connection state 1) or rejects when it fails (connection state 0)

**Comment by amustaque97** [comment]
okay! There could be some cases where in based on the events we need to perform some operation for example: once mongoose connection is successful we are opening some stream and when mongoose connection is disconnected. We want to close the opened stream. We want to manipulate stream based on the connection event... 


I actually tried with `readyState` variable but it is not realtime.

**Comment by jmcdo29** [comment]
Do you have access to these variables with just `mongoose`? Or in otherwords, is it our wrapper that is causing an issue, or does mongoose 6 (when the `asPromise()` was added) work slightly different than previous versions?

**Comment by amustaque97** [comment]
Yeah, till version 5 it was straightforward to implement. For version 6 I tested with the below code and it seems to be working.. I have attached screenshot for reference. In the screenshot, I'm using mongodb docker instance. 
```javascript
const mongoose = require('mongoose');

(async() => {
    const conn = mongoose.createConnection('mongodb://localhost:9972');
    conn.on('connected', function(){ console.log('Hi')});
    await conn.asPromise();
    conn.on('disconnected', function(){ console.log('Bye')});
})();
```

<img width="1792" alt="Screenshot 2022-03-20 at 10 52 08 AM" src="https://user-images.githubusercontent.com/21127788/159149470-815805b7-2af1-4cfb-ad0a-d4e226e159aa.png">

PS: If I write like this  ```await mongoose.createConnection(uri, mongooseOptions).asPromise()``` event emitter doesn't work. So even I'm not 100% sure whether it's an intended feature or `@nestjs/mongoose` wrapper is causing an issue.

**Comment by jmcdo29** [comment]
I think this is a side effect of how mongoose v6 is supposed to be used. Might want to try bringing it up with them and seeing what they say about it.

**Comment by amustaque97** [comment]
> I think this is a side effect of how mongoose v6 is supposed to be used. Might want to try bringing it up with them and seeing what they say about it.

I have created an issue there. https://github.com/Automattic/mongoose/issues/11545

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/Automattic/mongoose/issues/11545

**Comment by juona** [comment]
This should be reopened IMO. There is a problem here:

```typescript
return await lastValueFrom(
  defer(async () =>
    mongooseConnectionFactory(
      await mongoose
        .createConnection(uri as string, mongooseOptions)
        .asPromise(),
      mongooseConnectionName,
    ),
  ).pipe(handleRetry(retryAttempts, retryDelay)),
);
```

Quoting the maintainer of mongoose:

> The problem is that `const conn = await mongoose.createConnection('mongodb://localhost:27017').asPromise();` waits for Mongoose to finish connecting. So Mongoose is already connected when you register an event listener. The event listener works, you're just registering it too late.

So the consumer does not really have any way to listen to connection events.
