### ISSUE TITLE
Cannot connect to MongoDB with @nestjs/mongoose 9.0.3: createConnection called wrongly

### ISSUE THREAD

**Issue by alex-sadovsky** [nestjs/mongoose#1306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

On connection attempt getting this output:
Unable to connect to the database. Retrying (1)
Unable to connect to the database. Retrying (2)
...
 ERROR [ExceptionHandler] mongoose.createConnection(...).asPromise is not a function
TypeError: mongoose.createConnection(...).asPromise is not a function

Guys, `mongoose.createConnection()` already returns a Promise, no need to convert!
Please, remove `asPromise` call:
https://github.com/nestjs/mongoose/blob/f9793a65c3f46f954290599b8247fde0108b2379/lib/mongoose-core.module.ts#L59

### Minimum reproduction code

https://github.com/nestjs/mongoose/blob/f9793a65c3f46f954290599b8247fde0108b2379/lib/mongoose-core.module.ts#L59

### Steps to reproduce

1. Open https://github.com/nestjs/mongoose/blob/f9793a65c3f46f954290599b8247fde0108b2379/lib/mongoose-core.module.ts#L59
2. Remove `.asPromise()`

### Expected behavior

Connection to MongoDB successful.

### Package version

9.0.3

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
[Mognoose's `createConnection`](https://github.com/Automattic/mongoose/blob/master/lib/index.js#L272)  returns a [new `Connection` instance](https://github.com/Automattic/mongoose/blob/ba7c68ec1d959f30446d5b0c8a98c95edae2d7aa/lib/connection.js#L57) which has [a prototype (instance) method called `asPromise`](https://github.com/Automattic/mongoose/blob/ba7c68ec1d959f30446d5b0c8a98c95edae2d7aa/lib/connection.js#L1299). [Their docs do show that the `asPromise` is not necessary](https://mongoosejs.com/docs/api.html#mongoose_Mongoose-createConnection) though that wasn't necessary in earlier versions.

Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project) that shows this error happening.

**Comment by jmcdo29** [comment]
[Here's the original issue from when we added this change](https://github.com/nestjs/mongoose/issues/1082)

**Comment by kamilmysliwiec** [comment]
Update `mongoose` to the latest version

**Comment by alex-sadovsky** [comment]
@jmcdo29 , @kamilmysliwiec you're right, thanks for clarification
