### ISSUE TITLE
Option to not auto connect to mongo

### ISSUE THREAD

**Issue by ccontour** [nestjs/mongoose#1379]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am looking for some sort of flag or workflow that would let me create a NestJS application, using the mongoose module, but prevent it from immediately attempting to test / create a connection to mongodb

### Describe the solution you'd like

A minimal "if this flag is provided, just don't connect to mongodb" would be sufficient for my needs.

### What is the motivation / use case for changing the behavior?

I am looking to do a module scan of my nest application in order to extract some metadata from the providers, but not actually boot the app. This step is being performed inside of my build pipeline, with the results being written to a file when it's done. There isn't really an ideal database to be connecting to in this situation, and no data from mongo is needed in this configuration. All that's needed for me is the assembled nest application (prior to `init()`) 

This mongoose module attempts to form a connection to mongodb at construction time ([reference code](
https://github.com/nestjs/mongoose/blob/master/lib/mongoose-core.module.ts#L59)), instead of `onModuleInit` / `onApplicationBootstrap`, which prevents me from just omitting the `app.init()`.

I have attempted to work around the issue by utilizing [mongodb-memory-server](https://www.npmjs.com/package/mongodb-memory-server), but compatibility for that so far in my testing is pretty hit & miss

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
