### ISSUE TITLE
Allow the use of `refPath` field in the @Prop to use dynamic population.

### ISSUE THREAD

**Issue by tbhaxor** [nestjs/mongoose#1380]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

This starts with when I tried to implement audit log service with the following schema using class based technique from `@nestjs/mongoose`.

```ts
@Schema()
export class AuditLog {
   @Prop({type: String, required: true, enum: ["User", "Job"]})
   principalType: "User" | "Job"

   @Prop({type: SchemaTypes.ObjectId, refPath: "principalType", required: true})
   principalType: MongooseRef<User> | MongooseRef<Job>;
}

const AuditLogSchema = SchemaFactory.createForClass(AuditLog)
```

Now when I tried to create the document with principalType `User` and principal as object id of the user, it is getting saved. But, on retrieval with population, I am getting null.

```ts
const user = await this.userModel.findOne().exec()
console.log(!!user) // true

const audit = await this.auditModel.findOne().populate("principal").exec()
console.log(!!audit) // true
console.log(!!audit.principal) // false
console.log(audit.principalType) // User
console.log(audit.principal) // null
```

Also tried with `getModelToken("User")` or `getModelToken("Job")` and still it is not working. But with the old schema declaration it is working.

```ts
const AuditLogSchema = new mongoose.Schema({
   principalType: {type: String, required: true, enum: ["User", "Job"]},
   principal: {type: SchemaTypes.ObjectId, refPath: "principalType", required: true}
});
```

Now when I tried the old code, it is working

```ts
const user = await this.userModel.findOne().exec()
console.log(!!user) // true

const audit = await this.auditModel.findOne().populate("principal").exec()
console.log(!!audit) // true
console.log(!!audit.principal) // true
console.log(audit.principalType) // User
console.log(audit.principal.email === user.email) // true
```

### Describe the solution you'd like

Fix the codebase, so as to fix this issue.

### What is the motivation / use case for changing the behavior?

The class based schema definition is an elegant way and I don't want to go back to old way of mongoose schema declaration.

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
