### ISSUE TITLE
can't able to connect database using authentication

### ISSUE THREAD

**Issue by nickle72000** [nestjs/mongoose#143]
initial we try to  connect to database without username and password

MongooseModule.forRoot('mongodb://localhost/prospercare', { useCreateIndex: true,useNewUrlParser: true }), 
for security reason we add username and password. 
but after giving those details not able to connect to database using user name and password

MongooseModule.forRoot('mongodb://username:password@localhost/prospercare', { useCreateIndex: true,useNewUrlParser: true }), 

getting error as   MongoNetworkError: failed to connect to server [localhost] on first connect [MongoError: Not Authenticated.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
