### ISSUE TITLE
must provide connectionName explicitly after update from 9.0.3 to 9.1.0

### ISSUE THREAD

**Issue by Tobeyyyyy** [nestjs/mongoose#1437]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

231d3da

### Versions

9.0.3 -> 9.1.0

### Describe the regression

After updating to 9.1.0 we have to provide a `connectionName` in each `@InjectModel`. Since it is already defined elsewhere (see below), this leads to code duplication and is error-prone because the `connectionName` can be easily mistaken.

### Minimum reproduction code

This is the module that causes the error. We set a `connectionName` for each `Model` in the `forFeature` call.

**_database.module.ts_**
```ts
export enum CONNECTION_TYPES {
  PRIMARY = 'PRIMARY_CONNECTION',
  SECONDARY = 'SECONDARY_CONNECTION'
}

const uris = buildConnectionStrings()

const databaseModules = [
  MongooseModule.forRoot(uris.MONGO_PRIMARY_CONNECTION_STRING, {
    connectionName: CONNECTION_TYPES.PRIMARY
  }),
  MongooseModule.forRoot(uris.MONGO_SECONDARY_CONNECTION_STRING, {
    connectionName: CONNECTION_TYPES.SECONDARY
  }),
  MongooseModule.forFeature(
    [{ name: Portfolio.name, schema: PortfolioSchema }],
    CONNECTION_TYPES.PRIMARY
  ),
  MongooseModule.forFeature(
    [{ name: Company.name, schema: CompanySchema }],
    CONNECTION_TYPES.SECONDARY
  )
]

@Module({
  imports: [...databaseModules],
  exports: [...databaseModules]
})
export class DatabaseModule {}
```
Because we set the `connectionName` in the database-module.ts, it was not needed here anymore in version 9.0.3.

**_account.service.ts_**
```ts
@Injectable()
export class AccountService {
  constructor(
    @InjectModel(Portfolio.name) private portfolioModel: Model<Portfolio>
  ) {}
}
```

This behaviour changed in 9.1.0. Now you have to provide the `connectionName` everywhere.

**_account.service.ts_**
```ts
@Injectable()
export class AccountService {
  constructor(
    @InjectModel(Portfolio.name, CONNECTION_TYPES.PRIMARY_CONNECTION) private portfolioModel: Model<Portfolio>
  ) {}
}
```

### Expected behavior

This should continue to compile without errors.

### Error message

`[Nest] 3818  - 06/04/2022, 12:50:13 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the WatchlistService (?). Please make sure that the argument PortfolioModel at index [0] is available in the AppModule context.`

**Comment by kamilmysliwiec** [comment]
Thanks for sharing!

So this is intentional. It turns out there was a bug in `@nestjs/mongoose@9.0.3` that swallowed this error. This has been fixed in 9.2.0. If both models are registered under a specific connection, passing it as a second parameter of the `@InjectModel` annotation is (and should be) required.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
