### ISSUE TITLE
Indexes not sending to MongoDB

### ISSUE THREAD

**Issue by AuroPick** [nestjs/mongoose#1473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I create a schema and creating some indexes they are created but not sending to MongoDB

my schema

`paywall.schema.ts`
```ts
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose'
import { Document } from 'mongoose'

export type PaywallDocument = Paywall & Document

@Schema({ timestamps: true })
export class Paywall {
  @Prop({ type: String, enum: ['A/B', 'REGULAR'], required: true, default: 'REGULAR' })
  type: 'A/B' | 'REGULAR'

  @Prop({ type: String, unique: true, required: true })
  name: string

  @Prop({ type: Boolean, required: true, default: true })
  enable: boolean
}

export const PaywallSchema = SchemaFactory.createForClass(Paywall)

PaywallSchema.index({ enable: 1 })

console.log(PaywallSchema.indexes())

```
I can log them in console

![Ekran Resmi 2022-08-19 23 52 50](https://user-images.githubusercontent.com/53499802/185705460-c65f52c6-ef04-419a-89ff-0d696d48d277.png)

but not sending to MongoDB

![Ekran Resmi 2022-08-19 23 54 03](https://user-images.githubusercontent.com/53499802/185705611-0c0de6cb-816a-4629-91d5-3d9909f14f50.png)

### Minimum reproduction code

maybe after

### Expected behavior

They should be sended to MongoDB

### Package version

9.2.0

### mongoose version

6.5.2

### NestJS version

9.0.11

### Node.js version

18.6.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by AuroPick** [comment]
I have had read preference: secondary preferred. I updated it to primary. Now it is works.

update

```
readPreference=secondaryPreferred
```

to

```
readPreference=primary
```

**Comment by zodman** [comment]
it doesnt make sense ... I have the same problem ...
