### ISSUE TITLE
[discussion] Dynamic connection based on a resolver

### ISSUE THREAD

**Issue by Jeconias** [nestjs/mongoose#1495]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, you need specify the connection name when using `InjectModel` with the same schemas for multiples connection.

Example: 
```tsx
@Injectable()
export class FooService {
   constructor(
       @InjectModel(User.name) private userModel: Model<User>,
       @InjectModel(User.name, 'CONNECTION_NAME_TWO') private userModelTwo: Model<User>
       ) {} 
   ...
}
```

but, if we have a `@InjectDynamicModel` that get a model linked a database connection based on context? 

### Describe the solution you'd like

We can create a `forRootDynamicConnection` and `forFeatureDynamic` to use this feature and not breaks or increase complexity of existing functions.

The example of use:

```tsx 
// AppModule
@Module({
  imports: [
    MongooseModule.forRootDynamicConnection({
      resolver(dynamicKey) {
       
       // Here we can resolve based of request to create a new connection.

       // NOTES: 
       // - If the connection exists, it will not be recreated again.
       // - In this example, dynamicKey is a origin of request, but can be changed depending on `forFeatureDynamic` configuration.

        if (dynamicKey === 'dogs.com') {
          return { uri: 'mongodb://root:root@localhost:27017', dbName: 'dogs' };
        }

        return {
          uri: 'mongodb://root:root@localhost:27017',
          dbName: 'global-dogs',
        };
      },
    }),
    DogsModule,
  ],
})
export class AppModule {}
```

On dog module: 

```tsx
// DogModule
@Module({
  imports: [
    MongooseModule.forFeatureDynamic({
      models: [{ name: Dog.name, schema: DogSchema }],
     // resolverKey (optional): The resolver to generate the dynamicKey to `MongooseModule.forRootDynamicConnection`
     // factory (optional): inject | useFactory ...
    }),
  ],
  controllers: [DogsController],
  providers: [DogsService],
})
export class DogsModule {}
```
Now, on DogService we can do it:

```tsx
@Injectable()
export class DogsService {
  constructor(
    // Based on the current request, it will return a model with the correct database connection.
    @InjectDynamicModel(Dog.name) private readonly dogModel: Model<Dog>,
  ) {}

  async create(createDogDto: CreateCatDto): Promise<Dog> {
    const createdDog = new this.dogModel(createDogDto);

    return this.dogModel.create(createdDog);
  }

  async findAll(): Promise<Dog[]> {
    return this.dogModel.find().exec();
  }
}
```

On this example, the request with origin equal dogs.com will write on `dogs` database. With this, we can create more automated services and with the same code base, only changing the writing context.

I don't know if there is a way to create it using the current resource in this project, but I haven't found a solution. Please tell me if I'm overthinking it or not.

Thanks for reading!

Full example here: https://github.com/nestjs/mongoose/pull/1496

![Screen Recording 2022-08-30 at 14 34 58 (1)](https://user-images.githubusercontent.com/32512776/187509950-fcda32b0-8e65-4041-9391-2cea72c5a6cc.gif)

### What is the motivation / use case for changing the behavior?

Make the application grow easier, based on sub domains or other use cases.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
