### ISSUE TITLE
MongoError when i'm trying to connect to DocumentDB

### ISSUE THREAD

**Issue by rodbustamante** [nestjs/mongoose#1511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi everyone,

I'm trying to connect my app to documentDB using `ssl` and `ssl_ca_certs` as Amazon recommended here https://docs.aws.amazon.com/es_es/documentdb/latest/developerguide/connect_programmatically.html.

But i'm getting the error `MongoParseError: option ssl_ca_certs is not supported` and i don't see any option about this. Maybe i'm forgeting something?

Thanks

### Minimum reproduction code

.

### Steps to reproduce

.

### Expected behavior

.

### Package version

9.0.2

### mongoose version

6.2.3

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
