### ISSUE TITLE
Not Found any Good way to use mongoose useDb

### ISSUE THREAD

**Issue by rdev06** [nestjs/mongoose#1532]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Not found any method to pass db name from the request.

mongoose.connection.useDb('...dbName...') is used to choose db within same connection.
This support is not there internally with @nestjs/mongoose library.

Right now I am doing like this
`  private slotDateModel: (dbName: string) => Model<SlotDate>;
  constructor(@InjectConnection() private connection: Connection) {
    this.slotDateModel = (dbName): Model<SlotDate> => this.connection.useDb(dbName, {useCache: true}).model(SlotDate.name, SlotDateSchema);
  }`
  
  The issue with approach I am using is: for any kind of dependency issue the error thrown is 
  `Nest can't resolve dependencies of the SlotDateService (DatabaseConnection, ?). Please make sure that the argument SlotDateService at index [1] is available in the SlotDateModule context.`

### Describe the solution you'd like

  Instead of this, is it possible to use Dependency Injection directly directly to the constructor?
 
 Also need some way to pass collectionName dynamically like 
 
 collectionName => mongoose.model(collectionName, schema)

### What is the motivation / use case for changing the behavior?

Need more control to use this library
This will give us flexibility to work with multiple database and collection within same cluster.

**Comment by jmcdo29** [comment]
> `Nest can't resolve dependencies of the SlotDateService (DatabaseConnection, ?). Please make sure that the argument SlotDateService at index [1] is available in the SlotDateModule context.`

Looks like your `SlotDateService` is circular on itself somehow. 

Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
