### ISSUE TITLE
how do you filter the parent document in the find() based on the condition of the child document

### ISSUE THREAD

**Issue by zz541843** [nestjs/mongoose#1536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://user-images.githubusercontent.com/72638366/193209197-19d3061e-ca69-4027-bcd5-f1ec01919cb2.png)

If the Prop() type is Types.ObjectId, how do you filter the parent document in the find() based on the condition of the child document;

```
find({
  owner:{
    $elemMatch:{
      some_property: "1"
    }
  }
})

// error : Can't use $elemMatch

find({
  "owner.some_property":1 
})
// no effect, return always null
```

### Minimum reproduction code

.

### Expected behavior

Prop() type must be OwnerSchema for it to work

### Package version

8.1.3

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
