### ISSUE TITLE
Schema Model does not get injected

### ISSUE THREAD

**Issue by arianlopezc** [nestjs/mongoose#1555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you provide a name to your connection when declaring your mongoose connection, then the model associated with the connection stops being injected.

```
Error: Nest can't resolve dependencies of the AppService (?). Please make sure that the argument CatModel at index [0] is available in the AppModule context.

Potential solutions:
- If CatModel is a provider, is it part of the current AppModule?
- If CatModel is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing CatModel */ ]
  })

    at Injector.lookupComponentInParentModules (/Users/arianlc/Desktop/project-name/node_modules/@nestjs/core/injector/injector.js:241:19)
```

This was not happening in previous versions of nestjs/mongoose. After upgrading to the current version, my system started experiencing this.

### Minimum reproduction code

https://github.com/arianlopezc/mongoose-connection-name-test

### Steps to reproduce

npm install
npm run start

### Expected behavior

The application should start normally.
```
[Nest] 48151  - 10/15/2022, 7:04:44 PM     LOG [NestFactory] Starting Nest application...
[Nest] 48151  - 10/15/2022, 7:04:44 PM     LOG [InstanceLoader] MongooseModule dependencies initialized +25ms
[Nest] 48151  - 10/15/2022, 7:04:44 PM     LOG [InstanceLoader] MongooseCoreModule dependencies initialized +34ms
[Nest] 48151  - 10/15/2022, 7:04:44 PM     LOG [InstanceLoader] MongooseModule dependencies initialized +2ms
[Nest] 48151  - 10/15/2022, 7:04:44 PM     LOG [InstanceLoader] AppModule dependencies initialized +1ms
[Nest] 48151  - 10/15/2022, 7:04:44 PM     LOG [RoutesResolver] AppController {/}: +2ms
[Nest] 48151  - 10/15/2022, 7:04:44 PM     LOG [RouterExplorer] Mapped {/, GET} route +1ms
[Nest] 48151  - 10/15/2022, 7:04:44 PM     LOG [NestApplication] Nest application successfully started +1ms
```

### Package version

9.2.0

### mongoose version

6.6.5

### NestJS version

9.1.4

### Node.js version

18.10.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
You're missing the connection name in the `@InjectModel()` decorator. Second parameter. This is required if you use a named connection, just like it is in `forFeature()`
