### ISSUE TITLE
forFeatureAsync Move collection option from AsyncModelFactory into the useFactory return value

### ISSUE THREAD

**Issue by zaawee** [nestjs/mongoose#1594]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Collection name is currently a static property and it can be turned into a dynamic one using proper dependency injection.

### Describe the solution you'd like

Instead of having a collection under the AsyncModelFactory interface the collection property would be taken from the ModelDefinition type.

This is a breaking change because it will change the AsyncModelFactory interface. It can be solved by supporting both options with priority for one of them.

### What is the motivation / use case for changing the behavior?

I have a collection that might have name "x" on one deployment and name "y" on another.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
