### ISSUE TITLE
mongoose 7 is out!

### ISSUE THREAD

**Issue by TrejGun** [nestjs/mongoose#1690]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

no problem

### Describe the solution you'd like

no solution

### What is the motivation / use case for changing the behavior?

my motivation is to have up-to-date version of favourite software

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/mongoose/pull/1685
