### ISSUE TITLE
Upgrade to Mongoose version 7

### ISSUE THREAD

**Issue by heiba** [nestjs/mongoose#1713]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am suggesting we upgrade to the latest version of Mongoose, which is now version 7 https://github.com/Automattic/mongoose/releases

We wish to upgrade so that we have make use the latest features, bug-fixes, and security patches in the mongoose package.

Currently, as per my understanding, @nestjs/mongoose has [dev dependency on mongoose version 6.10](https://github.com/nestjs/mongoose/blob/121ccbb1ee570fa0fd52942822d0a3d4b3295a96/package.json#L41) with [a peer dependency on version 6.0.2](https://github.com/nestjs/mongoose/blob/121ccbb1ee570fa0fd52942822d0a3d4b3295a96/package.json#L54) 

### Describe the solution you'd like

I would like @nestjs/mongoose to depend on the latest version of mongoose version 7

### Teachability, documentation, adoption, migration strategy

References:
- https://github.com/Automattic/mongoose/releases

### What is the motivation / use case for changing the behavior?

Upgrading to the latest version of mongoose to make use of the latest features, bug-fixes, and security patches

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/mongoose/pull/1685
