### ISSUE TITLE
Don't extend `MongooseModuleOptions` from `Record<string, any>`

### ISSUE THREAD

**Issue by parzhitsky** [nestjs/mongoose#1742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The definition is too broad, property definitions are ignored, IntelliSense is not working, and there are no property suggestions (other than those from `Promise` type):

![image](https://user-images.githubusercontent.com/59528510/229110649-2672d7e7-85c0-4773-9ea4-f4a73787c527.png)

### Minimum reproduction code

https://tsplay.dev/wXv78m

### Steps to reproduce

1. Create an arbitrary _*.ts_ file
3. `npm i @nestjs/mongoose`
4. `import type { MongooseModuleOptions } from '@nestjs/mongoose/dist/interfaces/mongoose-options.interface'`
5. Define an object shaped as `MongooseModuleOptions`
6. Inspect object typings, properties, IntelliSense etc.

### Expected behavior

The definition is specific, property definitions are picked up, and IntelliSense is working:

![image](https://user-images.githubusercontent.com/59528510/229111158-0fd48e92-9c1d-4f06-b14d-66c53c75b18c.png)

### Package version

9.2.2

### Node.js version

18.15.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

This is specifically a typings issue. The only fix needed is to remove `extends Record<string, any>` from here:

https://github.com/nestjs/mongoose/blob/master/lib/interfaces/mongoose-options.interface.ts#L6

**Comment by kamilmysliwiec** [comment]
Would you like tor create a PR for this issue?

**Comment by parzhitsky** [comment]
Sure, on it

**Comment by parzhitsky** [comment]
PR ready 👆  (#1804), all checks have passed

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/mongoose/pull/1804
