### ISSUE TITLE
Using getters and setters with in super class

### ISSUE THREAD

**Issue by MarcusElevait** [nestjs/mongoose#1766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Let's say we have the following schema classes:
```typescript
export class SchemaA {
    @Prop({ 
        get: () => console.log('get schema a'), 
        set: () => console.log('set schema a') 
    })
    date: string;
}

@Schema()
export class SchemaB extends SchemaA {
     @Prop({ 
        get: () => console.log('get schema b'), 
        set: () => console.log('set schema b') 
    })
    title: string;
}
```

And now we make a `findOne` and a `create` call, then just the getters and setters of `SchemaB` are triggered.
Whereas when i make:

```typescript
export class SchemaA {
    @Prop({ 
        default: () => console.log('get schema a') 
    })
    date: string;
}

@Schema()
export class SchemaB extends SchemaA {
     @Prop({ 
        get: () => console.log('get schema b'), 
        set: () => console.log('set schema b') 
    })
    title: string;
}
```

and now i make the two calls, the `default` in `SchemaA` is triggered every time.

### Minimum reproduction code

can't provide running reproduction code

### Expected behavior

I expect the getter and setter to work also from the superclass.

### Package version

9.2.1

### mongoose version

6.5.5

### NestJS version

9.0.7

### Node.js version

18.15.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the mongoose repository
