### ISSUE TITLE
How do I integrate @casl/mongoose, it doesn't seem to compile through.

### ISSUE THREAD

**Issue by Hello202201** [nestjs/mongoose#1800]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

const mongoose = require('mongoose')
const { accessibleRecordsPlugin } = require('@casl/mongoose')

const Post = new mongoose.Schema({
  title: String,
  author: String
})

Post.plugin(accessibleRecordsPlugin)

module.exports = mongoose.model('Post', Post)

### Describe the solution you'd like

No solution

### What is the motivation / use case for changing the behavior?

I need @casl/mongoose and nestjs-mongoose together, how do the two work together

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
