### ISSUE TITLE
cache connection

### ISSUE THREAD

**Issue by Sekomer** [nestjs/mongoose#1835]
### Is there an existing issue that is already proposing this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to cache the database connection during development because on every save my server restarts and server tries to connect mongodb on the cloud, how can I overcome this.

### Describe the solution you'd like

a connection parameter that can cache the connection

### What is the motivation / use case for changing the behavior?

reduce dev time, reduce number of unnecessary connections to db

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
