### ISSUE TITLE
Unexpected ref function behaviour

### ISSUE THREAD

**Issue by piyushk96** [nestjs/mongoose#1847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`ref` function passed in schema options is being overridden by the static return value of that function during schema initialization. 

### Minimum reproduction code

https://codesandbox.io/p/sandbox/confident-antonelli-m7js5d

### Expected behavior

According to Mongoose documentation `ref` function should be called for every `populate()` call to determine the field's model according to the current document dynamically. 

But in the current scenario, the ref is called only once during initialization and uses that fixed return value for the rest of populate calls.

### Package version

10.0.0

### mongoose version

7.3.1

### Node.js version

16

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Other

https://github.com/nestjs/mongoose/blob/bbc84dfd592f7a62766125d3a4aad8baf1935ee8/lib/factories/definitions.factory.ts#L97-L98

ref in schema options is being overridden here

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
