### ISSUE TITLE
Unable to connect for non-SSL connections when specifying dbName in URI

### ISSUE THREAD

**Issue by DevHusariaSolutions** [nestjs/mongoose#1935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I've created new DB.
I'm able to connect to it via Mongo Compass.
I'm unable using this package specyfing only uri as:
```ts
MongooseModule.forRoot(DATABASE_URL)
```
getting error
` ERROR [MongooseModule] Unable to connect to the database. Retrying`

but if I remove dbName after slash from DATABASE_URL and use code below
```ts
MongooseModule.forRoot(DATABASE_URL, { dbName: 'my-db-name' })
```

It works

Wasted more hours than I could, so minimal info

### Minimum reproduction code

-

### Expected behavior

it connects correctly for uri with dbname

### Package version

10.0.1

### mongoose version

7.6.1

### NestJS version

10.2.7

### Node.js version

18.18

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
