### ISSUE TITLE
How to insert into a collection varying name ?

### ISSUE THREAD

**Issue by TechRova** [nestjs/mongoose#197]
How to insert into a collection varying name ?

That is , My chat backend stores chat in seprarate collections in this format 

`id1_id2 `

for example 

AA12_AA14 => member id 12 chatting with member id 14

AA15_AA16 => member id 15 chatting with member id 16

The tutorials only teaches to create a schema with a static name such such as Products 

I need dynamic names 

please help ?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
