### ISSUE TITLE
Nest can't resolve dependencies using yarn berry workspaces

### ISSUE THREAD

**Issue by ncstc1** [nestjs/mongoose#2156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This is similar to #1060 and discussed in many different places but no solution could be found.

Defining the peerDependencies as advised in #1060 did not help.
Also, the related item in the NestJS FAQ was taken into account without success (and nmHoistingLimits were defined).

This seems specific to yarn berry workspaces as the problem does not occur with a simple link or [Yalc](https://github.com/wclr/yalc)

See the details in the provided reproduction project: https://github.com/ncstc1/nestjs-yarn-berry-workspaces

```
[Nest] 76674  - 06/06/2024, 5:51:49 PM     LOG [NestFactory] Starting Nest application...
[Nest] 76674  - 06/06/2024, 5:51:49 PM     LOG [InstanceLoader] MongoModule dependencies initialized +7ms
[Nest] 76674  - 06/06/2024, 5:51:49 PM     LOG [InstanceLoader] MongooseModule dependencies initialized +0ms
[Nest] 76674  - 06/06/2024, 5:51:49 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the MongooseCoreModule (MongooseConnectionName, ?). Please make sure that the argument ModuleRef at index [1] is available in the MongooseCoreModule context.

Potential solutions:
- Is MongooseCoreModule a valid NestJS module?
- If ModuleRef is a provider, is it part of the current MongooseCoreModule?
- If ModuleRef is exported from a separate @Module, is that module imported within MongooseCoreModule?
  @Module({
    imports: [ /* the Module containing ModuleRef */ ]
  })

Error: Nest can't resolve dependencies of the MongooseCoreModule (MongooseConnectionName, ?). Please make sure that the argument ModuleRef at index [1] is available in the MongooseCoreModule context.

Potential solutions:
- Is MongooseCoreModule a valid NestJS module?
- If ModuleRef is a provider, is it part of the current MongooseCoreModule?
- If ModuleRef is exported from a separate @Module, is that module imported within MongooseCoreModule?
  @Module({
    imports: [ /* the Module containing ModuleRef */ ]
  })
```

### Minimum reproduction code

https://github.com/ncstc1/nestjs-yarn-berry-workspaces

### Expected behavior

The application starts as expected (as when yarn berry workspaces are not used)

### Package version

10.0.6

### mongoose version

8.4.1

### NestJS version

10.3.9

### Node.js version

18.18.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
