### ISSUE TITLE
Cannot populate using a dynamic ref inside an array of embedded discriminators

### ISSUE THREAD

**Issue by kiyui** [nestjs/mongoose#2182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

[Dynamic `ref` functions](https://mongoosejs.com/docs/populate.html#dynamic-ref) do not appear to work in `@nestjs/mongoose`. The ref function appears to be resolved at the time the schema is created, instead of at runtime.

This has been reported in the past here: https://github.com/nestjs/mongoose/issues/1847

This makes resolving the type for an [array of embedded discriminators](https://mongoosejs.com/docs/discriminators.html#embedded-discriminators-in-arrays) difficult in deeply nested or dynamic data structures where `refPath` may not be suitable.

### Minimum reproduction code

https://github.com/kiyui/nestjs-mongoose-ref-issue-reproduction

### Steps to reproduce

See the [proof of work section](https://github.com/kiyui/nestjs-mongoose-ref-issue-reproduction?tab=readme-ov-file#proof-of-work) in the reproduction repository.

### Expected behavior

The schema should not resolve a `ref` function's return at the time of its creation, but allow them to be run at runtime so the behaviour is the same as that of Mongoose.

The reproduction repository shows the difference of behaviour between this module and plain Mongoose and asserts this with integration tests for the two.

### Package version

10.0.6

### mongoose version

8.4.4

### NestJS version

10.3.10

### Node.js version

18.20.3, 20.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by smolinari** [comment]
Following.... :eyes: 

Scott

**Comment by kamilmysliwiec** [comment]
![image](https://github.com/user-attachments/assets/70da5094-03cf-4e64-b2e1-8cf9393bee95)

Fixed in 10.0.11
