### ISSUE TITLE
MongoDB Connections not Closing

### ISSUE THREAD

**Issue by cillaeslopes** [nestjs/mongoose#2188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

MongoDB connections doesn't seem to be closed after request is over. I've been monitoring the number of open connections on Compass and it gets higher and higher. 

When I start the application it starts with 13 connections
![image](https://github.com/nestjs/mongoose/assets/50371678/54be32da-7dd0-4894-9ce0-cbb2c7b8ad27)

If I simulate a high number of simultaneos requests it goes up to 35 connections 
![image](https://github.com/nestjs/mongoose/assets/50371678/2e7537fb-335c-47eb-b87d-c1c049f993f8)

Then it never gets back to 13 so it only gets higher.
![image](https://github.com/nestjs/mongoose/assets/50371678/338e7f8f-c690-4573-9cc4-290d5252d699)

### Minimum reproduction code

https://github.com/cillaeslopes/nest-mongo-test

### Steps to reproduce

- `npm i`
- `npm run start:watch`

Then in another terminal:
- `node scripts/high-traffic.js`

And observe mongodb connections with:
- `db.serverStatus().connections`

### Expected behavior

I'd expect the number of connections to get back to initial state once the requests are done

### Package version

10.0.2

### mongoose version

8.0.1

### NestJS version

10.3.2

### Node.js version

20.11.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
