### ISSUE TITLE
Cannot convert undefined to a BigInt

### ISSUE THREAD

**Issue by llegoelkelo** [nestjs/mongoose#2209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you add a bigint field to a schema you get an error: `Cannot convert undefined to a BigInt`

``` 
@Prop()
myBigInt?: bigint
```

Error:

TypeError: Cannot convert undefined to a BigInt
    at BigInt (<anonymous>)
    at Function.inspectTypeDefinition

### Minimum reproduction code

N/A

### Expected behavior

Schema should work correctly with BigInt which is fully supported by mongoose.

### Package version

10.0.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by llegoelkelo** [comment]
I created this repo https://codesandbox.io/p/devbox/elastic-shadow-zqc78l but only to find out that the problem has already been fixed in the latest version of the package.
