### ISSUE TITLE
Mongo connection count rises very high

### ISSUE THREAD

**Issue by jdegger** [nestjs/mongoose#2211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Unable to join on discord

![afbeelding](https://github.com/user-attachments/assets/08e95853-02a7-4261-bdfc-4ae0c81b96c3)

Threads get locked https://github.com/nestjs/mongoose/issues/2188

### Minimum reproduction code

https://github.com/cillaeslopes/nest-mongo-test/blob/main/scripts/high-traffic.js

### Steps to reproduce

- Multiple attempts to join discord, all give an error

### Expected behavior

- Joining should work

### Package version

10.0.6

### mongoose version

8.4.1

### NestJS version

10.0.6

### Node.js version

18.19.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

### Other

# Actual issue:
We are having the exact same problems as described in the issue here https://github.com/nestjs/mongoose/issues/2188

It contains a reproducible demo but the thread is locked without a way to add on it or know how it was resolved.

Discord does not allow us to join, so we have no way to reach out so this is desperate attempt in order to achieve one of the following:

- help with joining discord as it simply does not work despite mulitple attempts
- the solution of the linked issue is added to the actual github thread, this way other people encountering the problem can find the solution

Thanks in advance

**Comment by kamilmysliwiec** [comment]
There's probably not much we can do here since connection management is handled by Mongoose. It might be worth reporting this issue on their repository(?)
