### ISSUE TITLE
allow nestjs application to start even if MongoDB is temporarily unavailable.

### ISSUE THREAD

**Issue by vanHuong0202** [nestjs/mongoose#2216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

i am using nestjs with mongo db as secondary db, the issue is that if the mongo is temp unavailable, the nestjs app can not start and can not use other modules. So have any way or config that still allow the nestjs app can continue without nest/mongo module ?

### Minimum reproduction code

not available

### Expected behavior

Allow nestjs app can start if mongo serve is temp unavailable.

### Package version

10.0.6

### mongoose version

8.4.1

### NestJS version

10.3.8

### Node.js version

20

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
