### ISSUE TITLE
Data is not being saved in mongo DB

### ISSUE THREAD

**Issue by prashantgupta0206** [nestjs/mongoose#2250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am using below nest JS mongoose version and while saving the data in mongo DB the data is being saved there only **{ _id: new ObjectId("66e5778ac34747a66886439f") }** saved but actual payload is not saving.

"@nestjs/mongoose": "^10.0.10"
"mongoose": "^8.6.2"

Kindly provide solution how we can save data with example

### Minimum reproduction code

https://github.com/nestjs/mongoose

### Expected behavior

Actual payload should be saved in mongo db

### Package version

10.0.10

### mongoose version

8.6.1

### NestJS version

10.0.0

### Node.js version

20.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
