### ISSUE TITLE
Flags to control onApplicationShutdown to manually close connections

### ISSUE THREAD

**Issue by Kin9Jon9** [nestjs/mongoose#2309]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

 I'm using @nestjs/mongoose and kafka.js.

When I get a sigterm from K8S, it immediately closes the connection to @nestjs/mongoose (because there is already an onApplicationShutdown inside the library). Similarly, I wrote code to disconnect the consumer of kafkajs by applying an onApplicationShutdown to the provider that wraps kafkajs.

The problem is. I can't set @nejst/mongoose to disconnect, so the conformed messages are not processed and are missing (because the mongoose connection is already closed after receiving the sigterm).

I would like to control the onApplicationShutdown of @nestjs/mongoose to solve this problem.

### Describe the solution you'd like

Add the shutdownHook flag to the mongooseModule option. The default value is false. If true, it will ignore the onApplicationShutdown code written inside the library (it will not call .close()).

The cons is that if you set it to true and don't close the connection manually, you won't get disconnected.

### What is the motivation / use case for changing the behavior?

This issue is causing many kafka messages coming into my server to be missing.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?
