### ISSUE TITLE
Calling schema.index(...) in service ctor throws an exception

### ISSUE THREAD

**Issue by orgads** [nestjs/mongoose#2346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a schema for which I need some compound indexes. I create the indexes in the service ctor.

When running unit tests, the ctor is called multiple times, and apparently at some point the same schema instance is injected. When I call `schema.index(...)` it throws an exception: `MongooseError: Schema already has an index`.

This started with mongoose 8.9.x. See related https://github.com/Automattic/mongoose/issues/15109.

### Minimum reproduction code

```ts
import { Injectable } from '@nestjs/common';
import { InjectModel, Prop, Schema } from '@nestjs/mongoose';
import { IsString } from 'class-validator';
import { Model } from 'mongoose';

@Schema({ versionKey: false })
export class Foo {
  @IsString()
  @Prop({ index: true, type: String })
  bar!: string;
  @IsString()
  @Prop({ index: true, type: String })
  baz!: string;
}

@Injectable()
export class FooService {
  constructor(@InjectModel(Foo.name) private fooModel: Model<Foo>) {
    const { schema } = fooModel;
    schema.index({ bar: 1, baz: 1 }, { unique: true }); // This throws on second call
  }
}```

### Steps to reproduce

Instantiate FooService multiple times. The ctor is called, and the same schema is injected, then `index` fails.

### Expected behavior

Not sure what is the recommended to create the index only once. Can you advise?

### Package version

10.1.0

### mongoose version

8.9.2

### NestJS version

10.4.13

### Node.js version

22.11.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Other

_No response_

**Comment by kamilmysliwiec** [comment]
Why not register the index where you create the schema instead of doing it in the service constructor?

**Comment by orgads** [comment]
@kamilmysliwiec It is created using a class decorator. Where can I initialize the indexes?

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/techniques/mongodb#model-injection

`createForClass` returns a schema instance that you can call `index()` on

**Comment by orgads** [comment]
Thank you. This works.
