### ISSUE TITLE
Support for model discriminators

### ISSUE THREAD

**Issue by elias-garcia** [nestjs/mongoose#24]
Hi, is there any future plan for supporting mongoose discriminators?

https://mongoosejs.com/docs/discriminators.html

**Comment by juandav** [comment]
@kamilmysliwiec how discriminators are used with this library? it's possible?

**Comment by ssi-hu-tasi-norbert** [comment]
For me the discriminators array is undefined in the service.

**Comment by ssi-hu-tasi-norbert** [comment]
I have a workaround. In the service constructor I could add the discriminators and it works, but not with **save** method during creation, only the this.model.create(...   **save** works for update only. However would be nice to handle it in module after providers are imported.

**Comment by kamilmysliwiec** [comment]
Honestly, I do not understand the problem. Discriminators can be used in the same way as in the normal, pure mongoose app.

**Comment by kamilmysliwiec** [comment]
It would be great if you can share your solution with other people so they could use it as a reference :)

**Comment by matze1234** [comment]
@ssi-hu-tasi-norbert  can you share an example please?

**Comment by ssi-hu-tasi-norbert** [comment]
https://github.com/norbert-tasi/nestjs-mongoose

pls look for question.schema for discriminators. question.service does the trick.
I hope it helps you!

**Comment by Crackz** [comment]
I think this is the most elegant solution : 

Create your parent model as normal
```
	imports: [
		MongooseModule.forFeature([{ name: ANIMAL_MODEL_NAME, schema: AnimalSchema }]),
	],
```
To create a child model
```

	providers: [
		{
		provide: getModelToken(CAT_MODEL_NAME),
		useFactory: (animalModel) =>
			animalModel.discriminator(CAT_MODEL_NAME, CatSchema),
		inject: [getModelToken(ANIMAL_MODEL_NAME)]
	        }
	],

```


@kamilmysliwiec  Thank you so much !! great architecture !

**Comment by NenadJovicic** [comment]
@Crackz and how do you use it in some service?
how do you inject it?
with `@InjectModel(CAT_MODEL_NAME) catModel: Model<CatSchema>` ??

**Comment by NenadJovicic** [comment]
@Crackz and also, what if you need same child model in 2 different modules?
i tried to define them in 2 different modules, and was not able to do it, error was that specific model can't be defined twice

**Comment by NenadJovicic** [comment]
@ssi-hu-tasi-norbert but looking at that example, how can you know does it return you a model for email or range or datebox?
for example i want to query only for questions that are emails, and i want it to return me some `Document` that is generated for example from `EmailSchema`?
lets say i have created some type-safe document out of this schema and want to type output of some query to this document

**Comment by ssi-hu-tasi-norbert** [comment]
You set the discriminatorKey to whatever you want. In my example: discriminatorKey: 'kind'
The **kind** is a field/attribute just like others. You can query it.

**Comment by NenadJovicic** [comment]
I am sorry @Crackz , I made a mistake
this solution is working really nice.
I made a mistake because i use `{}` around this `discriminator` call, so i missed `return` inside of it
only problem with this is, if you need same model in 2 different modules, because you can't initialize it twice

but thanks for help

**Comment by Crackz** [comment]
Hi, @NenadJovicic 
i have not tested your given case because i use repository pattern. anyway i'd suggest you to export your child model which is one of the providers ! so any other module would import it . you will be able to @InjectModel(CHILD_MODEL_NAME) into it !

**Comment by ksugiarto** [comment]
> I think this is the most elegant solution :
> 
> Create your parent model as usual
> 
> ```
> 	imports: [
> 		MongooseModule.forFeature([{ name: ANIMAL_MODEL_NAME, schema: AnimalSchema }]),
> 	],
> ```
> 
> To create a child model
> 
> ```
> 
> 	providers: [
> 		{
> 		provide: getModelToken(CAT_MODEL_NAME),
> 		useFactory: (animalModel) =>
> 			animalModel.discriminator(CAT_MODEL_NAME, CatSchema),
> 		inject: [getModelToken(ANIMAL_MODEL_NAME)]
> 	        }
> 	],
> ```

Hi @Crackz, I'm sorry, I am a little bit lost on how to initialize or inject the model of `animalModel` in the provider here:

> 		useFactory: (animalModel) =>

 Could you kindly explain how to get it? 🙏

**Comment by NenadJovicic** [comment]
To use it in some service that is in same module, it is easy
Because you just do standard NestJS 
```typescript
constructor(@InjectModel(CAT_MODEL_NAME) private catModel: Model<CatDocument>) 
```
I only don't know how to use this same model in different module
@ksugiarto

**Comment by NenadJovicic** [comment]
@Crackz I also separate logic by modules, but had some case where I had to use same model in 2 different modules, and this solution was not working

**Comment by Crackz** [comment]
@NenadJovicic  i made a fully working example. i hope you find it useful 

https://github.com/Crackz/nest-mongoose-discriminator-test

**Comment by NenadJovicic** [comment]
I made it work without need for using same provider in multiple modules
But thank you 
It will be maybe useful sometimes @Crackz

**Comment by mkbrdigital** [comment]
> I made it work without need for using same provider in multiple modules
> But thank you
> It will be maybe useful sometimes @Crackz

@NenadJovicic 

How? Im facing same issue...

**Comment by sae13** [comment]
> Hey,
> 
> Finally I've could managed to solve the issue. The discrimination rules must be added in the service constructor after the model injected because in the schema file it didn't worked. You can close this issue since has a workaround.
> 
> Thanks for your great library!

can you send a example please

**Comment by vtrphan** [comment]
hi, i need to both define the discriminator AND use hooks (pre, post). So if i define the discriminator in a provider like the example of @Crackz , where can i then define the hooks (in other examples i see hooks are defined in the MoongooseModule.forFeatureAsync factory). Please advise.

**Comment by Crackz** [comment]
@vtrphan 
If you take a look at [this example](https://github.com/Crackz/nest-mongoose-discriminator-test.git)
you'd have a traditional mongoose schema so you can do it like this : 

```
import { Schema } from 'mongoose';

const CatSchema: Schema = new Schema(
	{
		bad: { 
			type: Boolean,
			default: false
		}
	},
	{ discriminatorKey: 'type' }
);

CatSchema.pre('save', function (next) {
	console.log('meow!!!!!!!!');
});


export { CatSchema };
```

**Comment by vtrphan** [comment]
@Crackz thanks for the example. I wanted to ask how i can do it using nestjs/mongoose style, i.e using class with decorator etc..

**Comment by vtrphan** [comment]
@Crackz any idea how i can use mongoose hooks and discriminator with nestjs/mongoose style (class with decorators) instead of traditional mongoose schema? Thanks

**Comment by Crackz** [comment]
@vtrphan sorry, I know nothing about nestjs/mongoose  decorators because i think it's unnecessary level of abstraction.
i'd recommend you creating a new issue asking @kamilmysliwiec

**Comment by johnfrades** [comment]
Hi @Crackz  i tried your solution but im getting an error 
`Cannot overwrite Processor model once compiled.
    at Function.Model.discriminator (/home/john/Documents/Projects/pchubbuilder/node_modules/mongoose/lib/model.js:1125:11)
`

i just provided the provider and i got this error.
This is my code 
```
@Module({
  imports: [
    MongooseModule.forFeature([
      PCBUILD_FEATURE,
      PART_FEATURE,
      NOTIFICATION_POOL_FEATURE,
      USER_FEATURE,
      PROCESSOR_FEATURE,
    ]),
  ],
  controllers: [PcBuildController],
  providers: [
    PcBuildService,
    {
      provide: getModelToken('Processor'),
      useFactory: partModel =>
        partModel.discriminator('Processor', ProcessorSchema),
      inject: [getModelToken(PART_FEATURE.name)],
    },
  ],
})
export class PcBuildModule {}
```

Do you know what is this error? Thanks!

**Comment by Crackz** [comment]
@johnfrades  Sorry For The Late Reply

i'd move PART_FEATURE to its own module and just import it into the child module
check animal module in the example

**Comment by Pong420** [comment]
@vtrphan Here is an example for [single-nested-discriminators](https://mongoosejs.com/docs/discriminators.html#single-nested-discriminators).
```ts
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Circle, CircleSchema } from './circle.schema';
import { Square, SquareSchema } from './square.schema';

@Schema({ discriminatorKey: 'kind' })
export class Shape {
  @Prop({ type: String, required: true })
  kind: string;
}

export const ShapeSchema = SchemaFactory.createForClass(Shape);

@Schema()
export class ShapeTest {
  @Prop({ type: ShapeSchema, required: true })
  shape: Shape;
}

export const ShapeTestSchema = SchemaFactory.createForClass(ShapeTest);

ShapeTestSchema.path('shape').discriminator(Circle.name, CircleSchema);
ShapeTestSchema.path('shape').discriminator(Square.name, SquareSchema);

```

You may also need the type definition, `@types/mongoose` is not supported yet ( [related issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30714) ). Remember to set `skipLibCheck` to `false` in tsconfig.json
```ts
declare module 'mongoose' {
  class SchemaType {
    discriminator<U extends Document>(name: string, schema: Schema): Model<U>;
  }
}
```

**Comment by WarKaa** [comment]
Hey @Pong420, is your repo still available ?

**Comment by Pong420** [comment]
@WarKaa Sorry, it was  deleted. 
you could take a looks on 
https://github.com/nestjs/mongoose/blob/master/tests/e2e/discriminator.spec.ts

or my other repo which using discriminators
https://github.com/taisiusyut/taisiusyut/tree/master/packages/server/src/modules/user/schemas

**Comment by nodejsdeveloperskh** [comment]
> I think this is the most elegant solution :
> 
> Create your parent model as usual
> 
> ```
> 	imports: [
> 		MongooseModule.forFeature([{ name: ANIMAL_MODEL_NAME, schema: AnimalSchema }]),
> 	],
> ```
> 
> To create a child model
> 
> ```
> 
> 	providers: [
> 		{
> 		provide: getModelToken(CAT_MODEL_NAME),
> 		useFactory: (animalModel) =>
> 			animalModel.discriminator(CAT_MODEL_NAME, CatSchema),
> 		inject: [getModelToken(ANIMAL_MODEL_NAME)]
> 	        }
> 	],
> ```
> 
> @kamilmysliwiec Thank you so much !! great architecture !

please share more info. if it is possible please create a repo for your solution

**Comment by Crackz** [comment]
I'd recommend using [the nest mongoose way](https://docs.nestjs.com/techniques/mongodb#discriminators) that you mentioned

you can find [my example here](https://github.com/Crackz/nest-mongoose-discriminator-test) It's for the ones who aren't comfortable with nest mongoose abstracting their schemas
