### ISSUE TITLE
typescript Model expects types which extend Document

### ISSUE THREAD

**Issue by ogiexela** [nestjs/mongoose#268]
If "@types/mongoose": "5.7.1", is used then it defines

```(alias) interface Model<T extends import("mongoose").Document, QueryHelpers = {}>```

which means  ```constructor(@InjectModel('Cat') private readonly catModel: Model<Cat>) {}``` will throw an error.

If Cat extends Document then creating cat instance requires implementing all the stuff from Document...

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
