### ISSUE TITLE
Add support to strongly typed Models

### ISSUE THREAD

**Issue by herbertpimentel** [nestjs/mongoose#293]
## I'm submitting a...

[ ] Regression 
[ ] Bug report
[X] Feature request
[X] Documentation issue or request
[ ] Support request 

## Current behavior
We cannot enjoy the entired benefit of typescript and mongoose types because models doesn't have how to be defined using strongly typed.

## Expected behavior
Be able to to define a type to be used to strongly type a Model

```typescript
interface ICat {
  name: string
};

MongooseModule.forFeature([{ name: 'Cat', schema: CatSchema, type: ICat }], 'cats')
```
```typescript
// this does not work if your are using @types/mongoose
// Model is not a Generic<T> class 
@InjectModel('User') private readonly users: Model<User> 

```

## What is the motivation / use case for changing the behavior?
Usage of the full power of typescript type definitions to intelisense code

**Comment by kamilmysliwiec** [comment]
We're tracking this here https://github.com/nestjs/docs.nestjs.com/issues/1066
