### ISSUE TITLE
Error when schema discriminators are used on embedded array fields

### ISSUE THREAD

**Issue by catchshyam** [nestjs/mongoose#3]
Hi,

One of my schema uses the discriminators as elaborated in this blog http://thecodebarbarian.com/mongoose-4.8-embedded-discriminators.html.

When I use such a schema with nest-mongoose, I get the following error,

....\node_modules\@nestjs\mongoose\mongoose.utils.js:4
    return `${JSON.stringify(model)}Model`;
                   ^
TypeError: Converting circular structure to JSON
 
I guess the code for generating model token will have to be changed since the schema JSON can not be serialized when there are discriminators.

Thanks.

**Comment by silvelo** [comment]
The way to generate the token have to much problems I make PR to solve #4 but this solve this problem too.

**Comment by kamilmysliwiec** [comment]
Fixed thanks to #5 by @silvelo. I'll push it together with the incoming release 👍
