### ISSUE TITLE
How to define a ref for schema using decorator

### ISSUE THREAD

**Issue by izundo-viennv** [nestjs/mongoose#483]
In the document, I don't know how to define a ref for schema using decorator

**Comment by kamilmysliwiec** [comment]
You can follow the mongoose docs (there is no difference) https://mongoosejs.com/docs/guide.html

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
