### ISSUE TITLE
one to many relation in mongoose with @Prop() decorator

### ISSUE THREAD

**Issue by Roma-Ghorjomeladze** [nestjs/mongoose#497]
I'm submitting an error in schema declaration with @Prop() decorator. I need one to many relation and when I'm writing 

  @Prop([{type: Types.ObjectId, ref: 'person'}])
  admins: any[];

the error occurs invalid schema configuration error: undefined is not a valid type within the array 'admins'. Am I doing something wrong?
![Screenshot from 2020-07-23 12-13-37](https://user-images.githubusercontent.com/60523959/88265260-39a2d480-ccde-11ea-8bd9-6953ccf868f9.png)
![Screenshot from 2020-07-23 12-14-41](https://user-images.githubusercontent.com/60523959/88265265-3ad40180-ccde-11ea-97d0-3ebe0c3529f1.png)

**Comment by Roma-Ghorjomeladze** [comment]
my bad. the relation need to be described like this:

@prop([{type: [Types.ObjectId], ref: 'person'}])
admins: any[];

**Comment by teleginzhenya** [comment]
Would be nice if it was written somewhere in docs :)

**Comment by jmcdo29** [comment]
@teleginzhenya want to make a PR to add it to the docs?

**Comment by teleginzhenya** [comment]
@jmcdo29 I can do it. Should I add it here (https://docs.nestjs.com/techniques/mongodb)?

**Comment by jmcdo29** [comment]
Yep, witymh the rest of the mongo docs

**Comment by teleginzhenya** [comment]
I did it here https://github.com/nestjs/docs.nestjs.com/pull/1475

**Comment by josepaiva94** [comment]
Are you sure that
```
@Prop({type: [Types.ObjectId], ref: 'person'})
admins: any[];
```
is the correct way? It is not populating the relation like this. If I do a one-to-one it populates.

**Comment by josepaiva94** [comment]
The correct way is
```
@Prop({ type: [{ type: Types.ObjectId, ref: 'person' }] })
admins: any[];
```
