### ISSUE TITLE
Module '"../node_modules/@nestjs/mongoose"' has no exported member 'MongooseModule'.

### ISSUE THREAD

**Issue by engpakravan** [nestjs/mongoose#501]
Hello Everyone , I Have Problem When Connecting Mongo .
`import { MongooseModule } from '@nestjs/mongoose';`
i was imported MongooseModule into my app.module.ts But This is Does not Work And This is Not Founded inside node_modules Folder Of @nestjs/mongoose
and this is inside of @nestjs/mongoose : 
`export * from './dist';`
and i was not see any dir name dist dist in this directory !
Help me pleaseeeeeeeee

**Comment by Tony133** [comment]
Hello,

Did you install it correctly as official documentation?

Try to reinstall it I put below the following commands:
```
$ npm install --save @nestjs/mongoose mongoose
$ npm install --save-dev @types/mongoose
```
and delete the dist folder before doing the commands I listed, just doing npm run start: dev auto recreates itself

Then in the ```app.module.ts``` file
add


```import { MongooseModule } from '@nestjs/mongoose';```

under

```import { Module } from '@nestjs/common';```

I hope I was helpful

Tony

**Comment by kamilmysliwiec** [comment]
Please, use our issue template and provide a minimal repository which reproduces your issue/problem.
