### ISSUE TITLE
mongoose global options debug, returnOriginal not supporting in forRoot

### ISSUE THREAD

**Issue by HedCET** [nestjs/mongoose#562]
i'm not able to pass `debug` & `returnOriginal` as options in `MongooseModule.forRoot()

```
    MongooseModule.forRoot(env.MONGO_URL, {
      connectionName: 'xxx',
      debug: env.NODE_ENV === 'production' ? false : true,
      returnOriginal: false,
      useCreateIndex: true,
      useFindAndModify: false,
      useNewUrlParser: true,
      useUnifiedTopology: true,
    }),
```

it's giving this warning

<img width="839" alt="Screenshot 2020-09-05 at 8 46 18 PM" src="https://user-images.githubusercontent.com/1794209/92308095-f1532380-efb8-11ea-99ac-a07ad7864d0d.png">

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
