### ISSUE TITLE
No MongoError to catch exceptions from mongoose

### ISSUE THREAD

**Issue by GeoPablo** [nestjs/mongoose#581]
## Bug Report
Following the guide from [NestJS](https://docs.nestjs.com/techniques/mongodb) you need `@nestjs/mongoose` and `mongoose` to interact with MongoDB.

The problem is that the errors threw by these modules are of type `MongoError`, but different from the object exported by `mongodb` package.

The problem is that there is no way to create an ExceptionFilter to handle mongo errors

## How to reproduce

```typescript
/**
 * * Dependencies
 */
import { ArgumentsHost, Catch, ExceptionFilter } from '@nestjs/common';

@Catch(MongoError)
export class MongoExceptionFilter implements ExceptionFilter {
  catch(exception: typeof MongoError, host: ArgumentsHost) {}
}
```
`MongoError` is not public

Here is a Github repo https://github.com/GeoPablo/nest-demo-mongo

**Comment by kamilmysliwiec** [comment]
See this https://github.com/nestjs/nest/issues/2664#issuecomment-525687266

and here's a fix for this one https://stackoverflow.com/a/61679809/6696689

**Comment by phanq2222** [comment]
@kamilmysliwiec when i import { MongoError } from 'mongoose/node_modules/mongodb'; it throw  'MongoError' is declared but its value is never read.ts(6133)
Cannot find module 'mongoose/node_modules/mongodb' or its corresponding type declarations.ts(2307)
Do you have other way ? thanks you
