### ISSUE TITLE
DocumentDB TLS Enabled

### ISSUE THREAD

**Issue by twigs67** [nestjs/mongoose#635]
I'm trying to connect to DocumentDB via TLS Enabled, but I don't see this as an option to pass within forRoot(). Maybe I'm missing it? 

Thanks

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
