### ISSUE TITLE
Initializing mongo ref as string instead of ObjectId

### ISSUE THREAD

**Issue by Pacheco95** [nestjs/mongoose#647]
## Bug Report
Accordingly to the [docs](https://docs.nestjs.com/techniques/mongodb#model-injection)

> In case you want to specify relation to another model, later for populating, you can use @Prop() decorator as well. For example, if Cat has Owner which is stored in a different collection called owners, the property should have type and ref. For example:

```ts
import { Types } from 'mongoose';
import { Owner } from '../owners/schemas/owner.schema';

@Prop({ type: Types.ObjectId, ref: Owner.name })
owner: Owner;
```

So, I tried it...

## Current behavior
Mongo is storing `targetUser` as an string

```js
{
  "_id" : ObjectId("5fb2999b0b7d61a62cdc88b8"),
  "targetUser" : "5faf0044ddfbfd93d02f6714",
  "__v" : 0
}
```

## Input Code
```ts
import { User } from "@/user/schemas/user.schema";
import { Prop, Schema } from "@nestjs/mongoose";
import { IsMongoId, IsOptional, IsString } from "class-validator";
import { Types } from "mongoose";

@Schema({ timestamps: true })
export default class NotificationDto {
  @IsString()
  @IsMongoId()
  @IsOptional()
  @Prop({ type: Types.ObjectId, ref: User.name })
  targetUser?: User;
}
```

```ts
// controller
@Post()
async create(
  @Body() notificationDto: NotificationDto,
): Promise<NotificationDto> {
  const notification = await this.notyService.create(notificationDto);
  return notification.toJSON();
}
```

```ts
// service
create(notification: NotificationDto): Promise<NotificationDocument> {
  return this.notificationModel.create(notification);
}
```

```jsonc
// request payload
{
  "targetUser": "5faf0044ddfbfd93d02f6714"
}
```

## Expected behavior
Mongo should store `targetUser` as an `ObjectId`:

```js
{
  "_id" : ObjectId("5fb2999b0b7d61a62cdc88b8"),
  "targetUser" : ObjectId("5faf0044ddfbfd93d02f6714"),
  "__v" : 0
}
```

## Environment

<pre><code>
Nest version: 7.5.1
 
For Tooling issues:
- Node version: 12.19.0
- Platform:
  $ cat /etc/os-release  
  NAME="Ubuntu"
  VERSION="20.04.1 LTS (Focal Fossa)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 20.04.1 LTS"
  VERSION_ID="20.04"
  HOME_URL="https://www.ubuntu.com/"
  SUPPORT_URL="https://help.ubuntu.com/"
  BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  VERSION_CODENAME=focal
  UBUNTU_CODENAME=focal

Others:

</code></pre>

**Comment by michal** [comment]
@Pacheco95 try `mongoose.Schema.Types.ObjectId` instead of `mongoose.Types.ObjectId`, 2nd one works only with arrays - something like this `@Prop({ type: [{ type: Types.ObjectId, ref: User.name }] })`

**Comment by Pacheco95** [comment]
@michal your solution works!

**Comment by kamilmysliwiec** [comment]
Updated the docs to reflect this change

**Comment by codiyer** [comment]
I think the docs should also mention that either `Schema` from `@nestjs/mongoose` or the `Schema` from `mongoose` should be imported using an alias as this is going to create conflict in all the cases where both needs to be imported. It would be better if `Schema` from `@nestjs/mongoose` can be renamed to something else, like `SchemaType` maybe.

**Comment by Pacheco95** [comment]
@kamilmysliwiec @michal 
I found that **does not matter** if you use `mongoose.Schema.Types.ObjectId` or `mongoose.Types.ObjectId`.
The id will always be stored as a string unless you explicitly assign an instantiated `ObjectId` to the field.

```ts
const noty = new this.notificationModel({
  targetUser: "5fb82cb95faac8843c5523cb"
});
await noty.save();
// Will store targetUser as string

const noty = await this.notificationModel.create({
  targetUser: "5fb82cb95faac8843c5523cb"
});
// Will store targetUser as string

const noty = new this.notificationModel();
noty.targetUser = new ObjectId("5fb82cb95faac8843c5523cb")
// Will store targetUser as ObjectId
```

Unfortunately I don't have time to provide an functional example now, but I'll do later.
