### ISSUE TITLE
how to connect to mongodb replica set 

### ISSUE THREAD

**Issue by jonnyshao** [nestjs/mongoose#653]
## Input Code

<pre><code>
// app.module.ts
import { Module, } from '@nestjs/common';
import * as path from 'path';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { ComponentModule } from './modules/component/component.module';
import { PageModule } from './modules/page/page.module';
import { FieldModule } from './modules/field/field.module';
import { V2Module } from './modules/v2/v2.module';
import { MongooseModule } from '@nestjs/mongoose';
import { ConfigModule, ConfigService } from 'nestjs-config';
@Module({
    controllers: [AppController,],
    providers: [AppService,],
    imports: [ComponentModule, PageModule, FieldModule, V2Module,
        ConfigModule.load(path.resolve(__dirname, 'config', '**/!(*.d).{ts,js}')),
        MongooseModule.forRootAsync({
            imports: [ConfigModule],
            useFactory: async (configService: ConfigService) => {
                return configService.get('database')
            },
            inject: [ConfigService]
        })
    ]
})
export class AppModule { }

</code></pre>
### configService.get('database') executed result
<pre><code>
{
  auto_reconnect: true,
  useNewUrlParser: true,
  useFindAndModify: false,
  uri: 'mongodb://1xx.x.x.1:27017,1x.x.x.1:27017,1x.x.x.1:27017/database',
  user: 'user',
  pass: 'pass',
  replset: 'set'
}
</code></pre>

## Mongoose example 

https://mongoosejs.com/docs/connections.html#replicaset_connections
<pre>
<code>
mongoose.connect('mongodb://user:pw@host1.com:27017,host2.com:27017,host3.com:27017/testdb');
</code>
</pre>
## Minimal reproduction of the problem with instructions

![image](https://user-images.githubusercontent.com/18613989/99654216-f8a4ac00-2a94-11eb-8341-5e9204427656.png)
## What is the motivation / use case for changing the behavior?

I can connect each database separately, but according to the mongoose example above, the connection keeps failing. What should I do? tanks!

## Environment

<pre><code>
Nest version: latest

 
For Tooling issues:
- Node version: latest 
- Platform:  Macos 10.15.7  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
