### ISSUE TITLE
the method  (mongoose.models),  What are the alternatives to

### ISSUE THREAD

**Issue by LeonYanghaha** [nestjs/mongoose#703]
I can use the method   ```  mongoose.models   ```To get all models in Mongoose, you can also get the specified model through  ```mongoose.model(modelName)```, but what about @ Nest / mongoose? Is there the same way

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
