### ISSUE TITLE
Nestjs MongoDB one to many have?

### ISSUE THREAD

**Issue by iPhonePKAndroid** [nestjs/mongoose#74]
can you help me?

mongoose one to one, one to many, many to many.

I need that.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions.

**Comment by muei** [comment]
@kamilmysliwiec Can you please show some samples that how to define one to many relations used by nestjs/mongoose ?
