### ISSUE TITLE
Upload file to mongodb on mongoose NestTS

### ISSUE THREAD

**Issue by siblonet** [nestjs/mongoose#813]
Please I’m new in NestTS and I’m not so deep in programme based on structures so please actually I have a NestTS project e-commerce, using mongodb on mongoose and it work perfectly but my only issue is how to upload images for products I’m uploading!
I tried many tutorials but as beginner I was completely confused and it getting  month I have been searching for help! So please guys I’m really begging if any body has a Youtube tutorial complete about how to upload file into mongodb ( schema, model, @Post() and @Get() controller to service, and if there is something else to add on connection setup  in module) I posted this in stark flow but no answer so please I’m begging all of you! I know it not easy and you’re all very busy but pls

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
