### ISSUE TITLE
Nest does not have file upload to database setup 

### ISSUE THREAD

**Issue by siblonet** [nestjs/mongoose#814]
@kamilmysliwiec, This is why nest will never ever grow up! And i try everything to stop nest from growing! [Discuss]()  here was the last place where I didn’t post that issue! Even on it different page social media I didn’t But nobody was able to it even Nest ! When you look at everywhere there is not documentation or tutorials for nest upload file to mongodb or to any database just because of your stupidness! it is clear that nest can’t do that! And it would have been better to tell the true!

**Comment by siblonet** [comment]
JMCD29 from Discuss, wasn’t to explain this in the platform

**Comment by kamilmysliwiec** [comment]
Thanks for sharing!
