### ISSUE TITLE
MongoDB Schema prop `unique` only works when `type` is set

### ISSUE THREAD

**Issue by MickL** [nestjs/mongoose#858]
## Current behavior
Setting the prop `unique: true` has no effect if `type` is not set.

I am not sure if this is intentional, but I do not see that documented so if it is intentional it should be documented why it is.

## Input Code
In the following schema the unique is not working:
```ts
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type CatDocument = Cat & Document;

@Schema()
export class Cat {
  @Prop({
    required: true,
    unique: true,
  })
  name: string;

  @Prop({required: true})
  age: number;

  @Prop()
  breed: string;
}

export const CatSchema = SchemaFactory.createForClass(Cat);
```

The following IS working:
```ts
@Prop({
    required: true,
    unique: true,
    type: String,
  })
  name: string;
```

## Expected behavior
`unique` may work without `type` as `required` does OR it should be documented.

## Environment

Nest version: 7.5.1

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by MickL** [comment]
My mistake, works as expected

**Comment by imSaharukh** [comment]
> My mistake, works as expected

where was the mistake bro? I'm facing the issue

**Comment by achapela** [comment]
> > My mistake, works as expected
> 
> where was the mistake bro? I'm facing the issue

Same here.. What is the mistake????

**Comment by imSaharukh** [comment]
> > > My mistake, works as expected
> > 
> > 
> > where was the mistake bro? I'm facing the issue
> 
> Same here.. What is the mistake????


set    useCreateIndex: true,
      autoIndex: true,
      
      like this 

  MongooseModule.forRoot(process.env.DATABASE_URL, {
      useCreateIndex: true,
      autoIndex: true,
    })

**Comment by achapela** [comment]
> > > > My mistake, works as expected
> > > 
> > > 
> > > where was the mistake bro? I'm facing the issue
> > 
> > 
> > Same here.. What is the mistake????
> 
> set useCreateIndex: true,
> autoIndex: true,
> 
> like this
> 
> ```
>   MongooseModule.forRoot(process.env.DATABASE_URL, {
>       useCreateIndex: true,
>       autoIndex: true,
>     })
> ```

I was sure I tried that and didn't work. It worked now. Awesome thank you
