### ISSUE TITLE
Schema custom collection name is ignored 

### ISSUE THREAD

**Issue by asafbenyamin** [nestjs/mongoose#882]
Hi,

I've created basic schema with a custom collection name,
and it seems like **sometimes** - it's been ignored by mongoose, and the default naming ("myobjects") applied.
I do know that the options object does work as expected, since my custom "createdAt" option does work.

`@Schema({
  collection: 'MyCollectionName',
  timestamps: { createdAt: '_created_at', updatedAt: '_updated_at' },
})
export class MyObject {
  @Prop({ type: String, default: someFunction })
  _id: string;

  @Prop()
  someProp: string;
}`

and then - 
`
export type MyDocument = MyObject & Document;
export type MyModel = Model<MyDocument>;

export const MySchema = SchemaFactory.createForClass<MyObject>(
  MyObject,
);
`

any ideas?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
